### ISSUE TITLE
Correct the access level for select LightLC message properties

### ISSUE THREAD

**Issue by eanderlind** [NordicSemiconductor/IOS-nRF-Mesh-Library#422] opened 2022-05-14 14:25 UTC
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/349e038531488ef15ed77f9a8b2881588d188214/nRFMeshProvision/Classes/Mesh%20Messages/Lighting/LightLCModeSet.swift#L39

Add `public` to controllerStatus property so that can access from code outside of the framework. Same comment applies to following messages:

LightLCModeSet/ LightLCModeSetUnacknowledged/ LightLSModeStatus

LightLCOccupancyModeSet / ..Unacknowledged / ..Status

**Comment by philips77** [comment] 2022-05-18 08:42
Duplicate of #421.

**Closed** 2022-05-18 08:42 UTC
