### ISSUE TITLE
Message discard issue

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#300] opened 2020-12-22 16:55 UTC
Hi,
I am encountering a new problem regarding message discarding based on the seq.
A device with friendship capabilities is taking a lot of time for provisioning and message reply, it fails most of the time.
Apparently a lot of messages got discarded along the way. I'm attaching the complete log but we noticed that in one line it appears to have discarded a message with a valid seq:

```
16:02:32.071 Network PDU (ivi: 0, nid: 0x7D, ctl: 0, ttl: 2, seq: 183, src: 0121, dst: 011A, transportPdu: 0x5A19408E37029C616CBB02CE44AA6217, netMic: 0x4BBE2AB8) received
16:02:32.071 Discarding packet (seqAuth: 180, expected > 182)
```
As you can see the PDU has seq: 183 but we discard it.

Could it be something related to the friendship management?

Thanks a lot.

**Platform details:**
 - Device: iPhone8
 - OS: iOS14
 - Library Version 2.2.3

[log.txt](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/files/5731087/log.txt)

**Comment by fiveagle** [comment] 2021-01-05 10:48
Hello and Happy New Year!!

Did you have any opportunity to give a read to the Logs attached? Unfortunately we are still stuck with this behaviour. 
Any help is really appreciated.

Thanks.

**Comment by philips77** [comment] 2021-01-05 14:36
Hi, I'm back at the office in 10 days, but I'll try to take a look before.

**Comment by fiveagle** [comment] 2021-01-22 09:28
Hi, 
did you have any chance to give this a try?

Thanks

**Comment by philips77** [comment] 2021-01-22 10:07
Hello!
I've resume working on mesh and will look into this issue. On branch *develop* there's version 3.0-beta1. Could you give it a try? I'm fixing some bugs I would there, but the final version should be released next week or in 2 weeks.
The API has slightly changed, check out #295.

**Comment by philips77** [comment] 2021-01-29 14:57
Hi,
Did you try the new version?

**Comment by fiveagle** [comment] 2021-02-03 16:52
Hi!
Unfortunately not. We are still in the middle of a release. Hope to have some time next weeks.

**Comment by philips77** [comment] 2021-11-18 14:25
Hello!
Can we close the issue? Do you have any other issues with the library?

**Comment by fiveagle** [comment] 2021-11-18 16:40
Hi, the problem is still pending on our side but it does not happen most of the time. I’ll open a new thread with more detailed informations if it is the case possibly after we manage to update the library.

**Comment by bhautikVolansys** [comment] 2022-07-07 13:04
@philips77 

I am facing the same issue Discarding packet because of sequence.

Steps
I have provisioned the node and then exported the database.
I have imported that database and the issue come on every command.

`Network PDU (ivi: 0, nid: 0x7E, ctl: 0, ttl: 7, seq: 0, src: 0022, dst: C000, transportPdu: 0x46F5B91CE83484F23CFD9D80, netMic: 0xBAF630CA) received
Discarding packet (seqAuth: 0, expected > 77)`

**Comment by philips77** [comment] 2023-10-12 14:39
I think I figured it out. Finally, after 1.5 year. Just AFTER releasing 4.0.0.

The issue seems to happen when the library receives all segments of a segmented message and sends the ACK.
However, the ACK fails to reach the target node, so it repeats the unacknowledged segments. 
The issue is, that the library incorrectly rejects them before is able to resend the ACK. The transmitter sends them over and over and never gets expected ACK.

**Closed** 2023-10-16 10:26 UTC
Labels: awaiting user input
