### ISSUE TITLE
Espressif timeout on sending

### ISSUE THREAD

**Issue by fiveagle** [NordicSemiconductor/IOS-nRF-Mesh-Library#175] opened 2019-10-11 09:10 UTC
**Describe the bug**
Hi,
I'm having some issue sending a CompositionDataGet to a Espressif gateway. It goes in TimeOut but reading the Gateway firmware log it looks like it is receiving too much segments. It continuously prints:

W (43991) BLE_MESH: Got segment for already complete SDU

and ends with:
```
W (60001) BLE_MESH: Client wrote 0x0000 instead enabling notify
W (99991) BLE_MESH: Client wrote 0x0000 instead enabling notify
W (140041) BLE_MESH: Client wrote 0x0000 instead enabling notify 
```
Thanks in advance for any help.

**Platform details:**
 - Device: iPhone8
 - OS:  iOS12.4.1
- Version: Last Commit e9be842730a0c0ae472279aa8d7e90115dc90ade

**Logs / Screenshots**

Nordic LOG:
```
W (384321) BLE_MESH: Got segment for already complete SDU
E (384821) BLE_MESH: send_seg, No multi-segment message contexts available
E (384821) BLE_MESH: dev_comp_data_get, Unable to send Config Composition Data Status
3:55 PM
W (443631) BLE_MESH: Client wrote 0x0000 instead enabling notify
```
Gateway Log:
```
I (647581) blemesh_prov_event_to_str:  EVENT: 4
I (647581) blemeshclient_prov_cb: event = 'Establish a BLE Mesh link event'
I (647581) blemeshclient_prov_cb: Node:Link:Open OK, bearer PB-GATT
W (648401) BLE_MESH: bt_mesh_attention, No Health Server context provided
I (648731) BLE_MESH: Primary Element: 0x0002
W (648741) BLE_MESH: bt_mesh_attention, No Health Server context provided
E (648761) BT_BTM: BTM_BleScan scan not active
E (648761) BLE_MESH: bt_le_scan_stop, Invalid status 6
E (648761) BLE_MESH: stopping scan failed (err -1)
I (648771) blemesh_prov_event_to_str:  EVENT: 5
I (648771) blemeshclient_prov_cb: event = 'Close a BLE Mesh link event'
I (648781) blemeshclient_prov_cb: ESP_BLE_MESH_NODE_PROV_LINK_CLOSE_EVT, bearer PB-GATT
I (648791) blemesh_prov_event_to_str:  EVENT: 10
I (648791) blemeshclient_prov_cb: event = 'Provisioning done event'
I (648801) blemeshclient_prov_complete: P406 Gateway is provisioned on mesh network
I (648811) blemeshclient_prov_complete: netkey index: 0x0025. gateway unicast address: 0x0002.
I (648821) blemeshclient_prov_complete: flags: 0x00, iv_index: 0x00000000
I (648831) NetKey: 53 b7 67 45 e8 88 aa 3f 35 36 13 19 8d 30 5d 8b
I (648831) fsm_event_handler: got event MESH_NODE_PROVISIONED
I (648841) ble_handler: registering netkey
I (648841) ble_handler: 53 b7 67 45 e8 88 aa 3f 35 36 13 19 8d 30 5d 8b
I (648851) BLE_GATT_service: custom_gatt_server_init: done
E (648861) nvs_init_and_open: Cannot open NVS 'plantconfnvs' with error: ESP_ERR_NVS_NOT_FOUND
I (648871) dispatch: old state 1
I (648871) dispatch: new state 2
I (648881) BLE_GATT_service: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (648881) BLE_GATT_service: 69 96 f5 fb 83 dc
I (648891) BLE_GATT_service: create attribute table successfully, the number handle = 6
I (648901) BLE_GATT_service: SERVICE_START_EVT, status 0, service_handle 52
E (656531) BLE_MESH: send_seg, No multi-segment message contexts available
E (656531) BLE_MESH: dev_comp_data_get, Unable to send Config Composition Data Status
W (658521) BLE_MESH: Got segment for already complete SDU
W (659481) BLE_MESH: Got segment for already complete SDU
W (659981) BLE_MESH: Got segment for already complete SDU
W (700711) BLE_MESH: Client wrote 0x0000 instead enabling notify
W (730131) BT_GATT: attribute value too long, to be truncated to 20
W (740691) BLE_MESH: Client wrote 0x0000 instead enabling notify
I (748171) BLE_GATT_service: ESP_GATTS_DISCONNECT_EVT, reason = 0x13
```

**Comment by philips77** [comment] 2019-10-11 15:52
If it's not a duplicate of 174, all this question on Nordic DevZone, as this is more related to the firmware side. Or provide logs from the iOS mesh library if you think the issue is in this lib.

**Comment by philips77** [comment] 2019-10-22 10:13
Hello,
Do you have logs from the iOS library as well?

**Comment by fiveagle** [comment] 2019-10-25 13:10
Hi,
with the last commits it now stops before composition data.
It prints:

Error: Local Provisioner has no Unicast Address assigned

when binding the AppKey.

Apparently the provisioner node is not inside the nodes array of MeshNetwork and the library fails getting its unicastAddress in row 469 of MeshNetworkManager.

Thank You.

**Comment by philips77** [comment] 2019-10-25 13:15
When you create a new network, using `manager.createNewMeshNetwork(name;by)`, the first provisioner is automatically added. It gets the first unicast address from the address range of the given provisioner. If you import a network on another phone, which has never had this network, you have to add a new provisioner and assign an address to it. Have a look at: 
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/c6ba36d900ebe6b16a65d3e599a224a27ddf5a80/Example/nRFMeshProvision/View%20Controllers/Settings/SettingsViewController.swift#L201-L220

**Comment by fiveagle** [comment] 2019-10-25 15:26
I'm not importing a meshNetwork yet. The localProvisioner is the actual phone the app is running on. But it is not inside the node array. I have deleted and rebuild the app but it's the same.
The strange thing is that I successfully managed to provision a mesh device and that the gateway espressif logs indicates that it has been successfully provisioned.

Thanks

**Comment by philips77** [comment] 2019-10-25 15:31
Node is not necessary for Provisioning, just for configuration. To assign am address and create node for Provisioner use `network.assign(address;for)`>

**Comment by philips77** [comment] 2019-10-25 15:35
Can you post a snippet how do you create the network and Provisioner?

**Comment by fiveagle** [comment] 2019-10-25 15:39
Same as the Sample App.

func createNewMeshNetwork() {
        // TODO: Implement creator
        connection?.close()
        
        let provisioner = Provisioner(name: UIDevice.current.name,
                                      allocatedUnicastRange: [AddressRange(0x0001...0x199A)],
                                      allocatedGroupRange:   [AddressRange(0xC000...0xCC9A)],
                                      allocatedSceneRange:   [SceneRange(0x0001...0x3333)])
        
        _ = meshNetworkManager.createNewMeshNetwork(withName: "P406MeshNetwork", by: provisioner)
        
        let network = meshNetworkManager.meshNetwork!
        let address = MeshAddress(0xC000)
        
        do {
            let group = try Group(name: "P406MeshGroup", address: address)
            try network.add(group: group)
            
        } catch {
            switch error as! MeshNetworkError {
            case .invalidAddress:
                print("The address \(address.debugDescription) is not a valid group address.")
            case .groupAlreadyExists:
                print("Group with address \(address.debugDescription) already exists.")
            default:
                print("An error occurred while creating the mesh group.")
            }
        }
        
        _ = meshNetworkManager.save()
        
        meshNetworkDidChange()
    }
    
    /// Sets up the local Elements and reinitializes the `NetworkConnection`
    /// so that it starts scanning for devices advertising the new Network ID.
    func meshNetworkDidChange() {
        connection?.close()
        
        let meshNetwork = meshNetworkManager.meshNetwork!
        
        // Set up local Elements on the phone.
        let element0 = Element(name: "Primary Element", location: .first, models: [
            Model(sigModelId: 0x1000, delegate: GenericOnOffServerDelegate()),
            Model(sigModelId: 0x1002, delegate: GenericLevelServerDelegate()),
            Model(sigModelId: 0x1001, delegate: GenericOnOffClientDelegate()),
            Model(sigModelId: 0x1003, delegate: GenericLevelClientDelegate())
        ])
        let element1 = Element(name: "Secondary Element", location: .second, models: [
            Model(sigModelId: 0x1000, delegate: GenericOnOffServerDelegate()),
            Model(sigModelId: 0x1002, delegate: GenericLevelServerDelegate()),
            Model(sigModelId: 0x1001, delegate: GenericOnOffClientDelegate()),
            Model(sigModelId: 0x1003, delegate: GenericLevelClientDelegate())
        ])
        meshNetworkManager.localElements = [element0, element1]
        
        connection = NetworkConnection(to: meshNetwork)
        connection!.dataDelegate = meshNetworkManager
//        connection!.logger = self
        meshNetworkManager.transmitter = connection
        connection!.open()
    }

**Comment by fiveagle** [comment] 2019-10-28 16:27
Hi,
apparently I deleted the provisioner node while retrieving the node with address 2 but getting instead the node at address 1. Looks like this code below enabled this behaviour. Is this an expected behaviour? Should I be allowed to delete the provisioner node?

Anyway now I get` Request timed out` on send ConfigAppKeyAdd, both on gateway and on the devices. I have set `acknowledgmentMessageTimeout` to 120.

ThankYou very much.

```
var lastUnicastAddress: UInt16 {
        // Provisioner may not have any elements
        let allocatedAddresses = Address(elementsCount > 0 ? elementsCount : 1)
        return unicastAddress + allocatedAddresses - 1
    }
```

**Comment by philips77** [comment] 2019-10-29 05:27
Yes, it is possible to remove a Provisioner, even the last one. But this code you gave shouldn't do anything, it's not mutating.
For the second issue please post some logs.

**Comment by fiveagle** [comment] 2019-10-29 08:59
Ok. This is when I set 120 as timeout

```
Adding Application Key...
2019-10-28 17:58:59.488338+0100 P406[1928:1440681] [FoundationModel] Sending ConfigAppKeyAdd(networkKeyIndex: 10, applicationKeyIndex: 0, key: 16 bytes) to: 000B
2019-10-28 17:58:59.491127+0100 P406[1928:1440681] [Access] Sending Access PDU (opcode: 0x 0, parameters: 0x0A00001A9718F774F5341608E4B5B91B622165)
2019-10-28 17:58:59.497024+0100 P406[1928:1440681] [UpperTransport] Sending Upper Transport PDU (encrypted data: 0x26C7AB53B094B0925810639D59A004225B98CF2A, transMic: 0x249AB97D) encrypted using key: 1888_592's Device Key
2019-10-28 17:58:59.499186+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 0, segN: 1, data: 0x26C7AB53B094B0925810639D)
2019-10-28 17:58:59.501745+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 282, src: 0001, dst: 000B, transportPdu: 0xF985F108E88155C3BD4262FDDB7333E3, netMic: 0xB10D6DD1) encrypted using propels Network Key (index: 10)
2019-10-28 17:58:59.502967+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 1, segN: 1, data: 0x59A004225B98CF2A249AB97D)
2019-10-28 17:58:59.505711+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 283, src: 0001, dst: 000B, transportPdu: 0x985E1918D68AF548C5DCC3EF9480C9D2, netMic: 0x6A5BA897) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:00.056036+0100 P406[1928:1440896] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 0, segN: 1, data: 0x26C7AB53B094B0925810639D)
2019-10-28 17:59:00.058835+0100 P406[1928:1440896] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 284, src: 0001, dst: 000B, transportPdu: 0x035698264AF157A4C93B26F32F22B4B2, netMic: 0x9A8C6B85) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:00.060127+0100 P406[1928:1440896] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 1, segN: 1, data: 0x59A004225B98CF2A249AB97D)
2019-10-28 17:59:00.063845+0100 P406[1928:1440896] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 285, src: 0001, dst: 000B, transportPdu: 0xB86925B73242775752B8220C43013BF7, netMic: 0x6F65F63E) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:00.610150+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 0, segN: 1, data: 0x26C7AB53B094B0925810639D)
2019-10-28 17:59:00.613560+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 286, src: 0001, dst: 000B, transportPdu: 0xC2BEAAD6538C7815987A37E3F5C58B6D, netMic: 0x77171BA0) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:00.615112+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 1, segN: 1, data: 0x59A004225B98CF2A249AB97D)
2019-10-28 17:59:00.618671+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 287, src: 0001, dst: 000B, transportPdu: 0x59090A13B7E1D38D8CA1A1B35EE723B4, netMic: 0xCF1FCA15) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:01.160200+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 0, segN: 1, data: 0x26C7AB53B094B0925810639D)
2019-10-28 17:59:01.163653+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 288, src: 0001, dst: 000B, transportPdu: 0x64E5460C5E60F8F14B8D495745080C6F, netMic: 0x1C4ED542) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:01.165397+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 1, segN: 1, data: 0x59A004225B98CF2A249AB97D)
2019-10-28 17:59:01.168887+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 289, src: 0001, dst: 000B, transportPdu: 0x0E103CF792637845D55EF1C6F5F17582, netMic: 0x7872A627) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:01.718256+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 0, segN: 1, data: 0x26C7AB53B094B0925810639D)
2019-10-28 17:59:01.722104+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 290, src: 0001, dst: 000B, transportPdu: 0x638D67C5B6D583087ED0696E43EBF590, netMic: 0xDC27EA92) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:01.723610+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 1, segN: 1, data: 0x59A004225B98CF2A249AB97D)
2019-10-28 17:59:01.727488+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 291, src: 0001, dst: 000B, transportPdu: 0xD02156240EABA9A8563169A71539A969, netMic: 0xC3CF5884) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:02.276882+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 0, segN: 1, data: 0x26C7AB53B094B0925810639D)
2019-10-28 17:59:02.280334+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 292, src: 0001, dst: 000B, transportPdu: 0x51AC9D046E23695B6C4F82E833EFA894, netMic: 0xE96D8EDC) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:02.281897+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 282, segO: 1, segN: 1, data: 0x59A004225B98CF2A249AB97D)
2019-10-28 17:59:02.285409+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 293, src: 0001, dst: 000B, transportPdu: 0x17821339E1CBA225D37961B294AB1DBC, netMic: 0x9E6E0766) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:04.944659+0100 P406[1928:1440819] [Access] Resending Access PDU (opcode: 0x 0, parameters: 0x0A00001A9718F774F5341608E4B5B91B622165)
2019-10-28 17:59:04.946164+0100 P406[1928:1440819] [UpperTransport] Sending Upper Transport PDU (encrypted data: 0x27D6A1873A4A2E2D19A827DE635B61BDF1587AE1, transMic: 0xE8F55D8D) encrypted using key: 1888_592's Device Key
2019-10-28 17:59:04.946926+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 0, segN: 1, data: 0x27D6A1873A4A2E2D19A827DE)
2019-10-28 17:59:04.950063+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 294, src: 0001, dst: 000B, transportPdu: 0xBD71E26B057360A50D96EB18BFB51686, netMic: 0xA3F8C371) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:04.951562+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 1, segN: 1, data: 0x635B61BDF1587AE1E8F55D8D)
2019-10-28 17:59:04.955325+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 295, src: 0001, dst: 000B, transportPdu: 0x3B6FF33A4D191F3B2CA9EC3EAF709185, netMic: 0x60E74E55) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:05.499570+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 0, segN: 1, data: 0x27D6A1873A4A2E2D19A827DE)
2019-10-28 17:59:05.502965+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 296, src: 0001, dst: 000B, transportPdu: 0x5DD3C0765B63EDF3795CEAF870F18ED5, netMic: 0x7045EC50) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:05.505076+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 1, segN: 1, data: 0x635B61BDF1587AE1E8F55D8D)
2019-10-28 17:59:05.508356+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 297, src: 0001, dst: 000B, transportPdu: 0x6EE3E9585E71DC814C39B6E977A2A3B7, netMic: 0x695ADA56) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:06.043702+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 0, segN: 1, data: 0x27D6A1873A4A2E2D19A827DE)
2019-10-28 17:59:06.046808+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 298, src: 0001, dst: 000B, transportPdu: 0xBCA37AC6D060BBF6EF5B908D67370B74, netMic: 0x071E2B16) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:06.049360+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 1, segN: 1, data: 0x635B61BDF1587AE1E8F55D8D)
2019-10-28 17:59:06.053282+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 299, src: 0001, dst: 000B, transportPdu: 0x4CAFF98BD81F8580CABA7EB7EB4BC009, netMic: 0x8BA23E8E) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:06.527182+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 0, segN: 1, data: 0x27D6A1873A4A2E2D19A827DE)
2019-10-28 17:59:06.530608+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 300, src: 0001, dst: 000B, transportPdu: 0x4FEAB693F0B2ED8BBA70BC311296F9EB, netMic: 0xA71A7AAB) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:06.532197+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 1, segN: 1, data: 0x635B61BDF1587AE1E8F55D8D)
2019-10-28 17:59:06.535813+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 301, src: 0001, dst: 000B, transportPdu: 0xD1025DBE31103BFEF9A45910E4798460, netMic: 0xF186CC89) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:06.676934+0100 P406[1928:1440819] [Network] Secure Network Beacon (Network ID: F5B08F855DB1DAC8, IV Index: 0, Key Refresh Flag: false, IV Update active: false) receieved (decrypted using key: propels Network Key (index: 2))
2019-10-28 17:59:07.026942+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 0, segN: 1, data: 0x27D6A1873A4A2E2D19A827DE)
2019-10-28 17:59:07.028843+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 302, src: 0001, dst: 000B, transportPdu: 0xB3FC72D549944D3E45C32856EA6EFE01, netMic: 0x128D3E68) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:07.029613+0100 P406[1928:1440681] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 1, segN: 1, data: 0x635B61BDF1587AE1E8F55D8D)
2019-10-28 17:59:07.031594+0100 P406[1928:1440681] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 303, src: 0001, dst: 000B, transportPdu: 0x21460ACAF66D3505EB595568C1FA63F7, netMic: 0x5A41F713) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:07.577260+0100 P406[1928:1440896] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 0, segN: 1, data: 0x27D6A1873A4A2E2D19A827DE)
2019-10-28 17:59:07.580685+0100 P406[1928:1440896] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 304, src: 0001, dst: 000B, transportPdu: 0xF8E4EB39A43B4F261E27F8E7B229A890, netMic: 0xDBC3BDAB) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:07.582218+0100 P406[1928:1440896] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 294, segO: 1, segN: 1, data: 0x635B61BDF1587AE1E8F55D8D)
2019-10-28 17:59:07.586270+0100 P406[1928:1440896] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 305, src: 0001, dst: 000B, transportPdu: 0xBECE0EE43729BE5336D430ACA5EFEB52, netMic: 0xABC9E0A3) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:15.749081+0100 P406[1928:1440945] [Access] Resending Access PDU (opcode: 0x 0, parameters: 0x0A00001A9718F774F5341608E4B5B91B622165)
2019-10-28 17:59:15.750641+0100 P406[1928:1440945] [UpperTransport] Sending Upper Transport PDU (encrypted data: 0xE4A70789829588583AA37EDDA3BDB3BE02BCC3E1, transMic: 0xDA048FB0) encrypted using key: 1888_592's Device Key
2019-10-28 17:59:15.751528+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 0, segN: 1, data: 0xE4A70789829588583AA37EDD)
2019-10-28 17:59:15.754851+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 306, src: 0001, dst: 000B, transportPdu: 0x3A4C6DA7EB87458AB4634D5A8B138427, netMic: 0x39FFB139) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:15.756860+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 1, segN: 1, data: 0xA3BDB3BE02BCC3E1DA048FB0)
2019-10-28 17:59:15.760259+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 307, src: 0001, dst: 000B, transportPdu: 0x28002DF2C0C5E2A3A2B8283FDE6621F7, netMic: 0x154020D8) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:16.311207+0100 P406[1928:1440946] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 0, segN: 1, data: 0xE4A70789829588583AA37EDD)
2019-10-28 17:59:16.314628+0100 P406[1928:1440946] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 308, src: 0001, dst: 000B, transportPdu: 0x77F86E58E7ED7178EE523582307933B0, netMic: 0x539D348C) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:16.316103+0100 P406[1928:1440946] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 1, segN: 1, data: 0xA3BDB3BE02BCC3E1DA048FB0)
2019-10-28 17:59:16.319823+0100 P406[1928:1440946] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 309, src: 0001, dst: 000B, transportPdu: 0x65EBAB826BCB6F2AA4B6155D2E0E0FC6, netMic: 0xC56447AC) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:16.861187+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 0, segN: 1, data: 0xE4A70789829588583AA37EDD)
2019-10-28 17:59:16.864690+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 310, src: 0001, dst: 000B, transportPdu: 0xEA8D0821F5AA21DF72CF81445489A032, netMic: 0xBDE44469) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:16.866362+0100 P406[1928:1440819] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 1, segN: 1, data: 0xA3BDB3BE02BCC3E1DA048FB0)
2019-10-28 17:59:16.869886+0100 P406[1928:1440819] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 311, src: 0001, dst: 000B, transportPdu: 0xD774902AB0F63C86C2D947D9C25E9EDC, netMic: 0xE90ECC32) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:17.411264+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 0, segN: 1, data: 0xE4A70789829588583AA37EDD)
2019-10-28 17:59:17.414752+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 312, src: 0001, dst: 000B, transportPdu: 0x3B438C04A84E9A09AAFB8F828038AF77, netMic: 0xA630BED7) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:17.417259+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 1, segN: 1, data: 0xA3BDB3BE02BCC3E1DA048FB0)
2019-10-28 17:59:17.420397+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 313, src: 0001, dst: 000B, transportPdu: 0xB2D552C05060371C8E92D48ECF21B7B5, netMic: 0xC60602EC) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:17.964906+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 0, segN: 1, data: 0xE4A70789829588583AA37EDD)
2019-10-28 17:59:17.968318+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 314, src: 0001, dst: 000B, transportPdu: 0x3C50A3F0B0FCDEB17B869FD2D0D9AAEB, netMic: 0x0C71E309) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:17.969817+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 1, segN: 1, data: 0xA3BDB3BE02BCC3E1DA048FB0)
2019-10-28 17:59:17.973669+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 315, src: 0001, dst: 000B, transportPdu: 0x42B9107C1AFD204F6B961B02B70AFEA8, netMic: 0xD5B02FD4) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:18.514986+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 0, segN: 1, data: 0xE4A70789829588583AA37EDD)
2019-10-28 17:59:18.518390+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 316, src: 0001, dst: 000B, transportPdu: 0xDAC52789546FE75840624E6D09879ADD, netMic: 0x27E71020) encrypted using propels Network Key (index: 10)
2019-10-28 17:59:18.519983+0100 P406[1928:1440945] [LowerTransport] Sending Segmented Access Message (akf: 0, szmic: 0, seqZero: 306, segO: 1, segN: 1, data: 0xA3BDB3BE02BCC3E1DA048FB0)
2019-10-28 17:59:18.523837+0100 P406[1928:1440945] [Network] Sending Network PDU (ivi: 0, nid: 0x58, ctl: 0, ttl: 5, seq: 317, src: 0001, dst: 000B, transportPdu: 0x6CF6D8952F63E69B26086C2B62E09365, netMic: 0x11423859) encrypted using propels Network Key (index: 10)
Connection did close
```

**Comment by philips77** [comment] 2019-10-29 09:23
Do you have the `transmitter` set to a Bearer and `bearer.delegate` to `MeshNetworkManager`? Looks like either you are not sending any data, or the received data are not passed to the manager.

**Comment by philips77** [comment] 2019-10-29 10:34
You may also set the `logger` to the `NetworkConnection`, or the a `GattBearer` that you are using to get bearer logs as well.

**Comment by fiveagle** [comment] 2019-10-29 16:42
I have been updating my `NetworkConnection` with yours from the Sample app. 
I have introduced a delay between the provisioning and the first config send. I am pretty sure that my devices could and probably needs, to reboot during the process. When it happens I don't get any `GattBearerDelegate` calls in my class notifying the node is connected again. And then my process gets hanged till the timeout. I use the `whenConnected` method from your sample app.
My delegates seems to be set correctly because I receive the outside the configurations. I don't receive any callback also when I try to send a `VendorMessage`. 
When my other nordic devices don't reboot the config process goes successfully to the end.

Thansks

**Comment by philips77** [comment] 2019-10-29 19:36
Oh yes, after the device is provisioned it will reboot and needs some time before it starts advertising again. But this takes around 10 seconds in our mesh sdk 3.2. Then the connection, which also takes time as the connection interval is long. But eventually Composition Get succeeds.

**Comment by philips77** [comment] 2019-11-04 09:51
Hi, can this issue be closed now?

**Closed** 2019-11-04 14:41 UTC
Labels: awaiting user input, question
