### ISSUE TITLE
Support CocoaPods ?

### ISSUE THREAD

**Issue by trusbe** [NordicSemiconductor/IOS-nRF-Mesh-Library#41] opened 2018-06-25 08:13 UTC
This can be synchronized directly to the latest update.

**Comment by mostafaberg** [comment] 2018-06-25 08:50
The library is currently working as a private pod due to some difficulties with OpenSSL.
You may use it as a pod internally, but you'll need to modify the OpenSSL dependency and remove it form our Pod and add it to your dependency list, we will have a fix for that eventually and release as a public pod, but for now this is not fully supported.

Also, this is a duplicate of #23 so I'll close this for now and you can follow that issue instead.

as soon as we fix that, you'll be notified when the issue is resolved and closed so I'd suggest you follow the issue #23 instead.

thanks a lot for your feedback.

**Closed by mostafaberg** 2018-06-25 08:50 UTC

**Comment by trusbe** [comment] 2018-06-25 11:16
Thanks for your feedback, 

Oh, I got it, Waiting for good news.
